version: '3'

services:
  weblibrary:
    image: weblibrary:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_weblibrary$
    volumes:
      - C:\WIP\Sandbox\DotNetCore\source\WebLibrary:/app
      - C:\Users\dheiser\vsdbg:/remote_debugger:ro
      #- $nuget_user_folder_weblibrary$:/root/.nuget/packages:ro
#$nuget_fallback_packages_volume_mapping_weblibrary$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_weblibrary$ bin/Debug/netcoreapp2.0/WebLibrary.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
